apiVersion: v1
kind: Secret
metadata:
  name: jarvis-secret
stringData:
  OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:mSLcokjsYwUWvw6b1NZj/8gdJjvotzpybMjrOrAfc2zr4PDqWZ4UlTUjARiBsq+QaZtW1uQ1wuJjz27iB3urWQ==,iv:QuZnTQ/MQtswgotyUEkE/PrI7GUkS9h6HFOHVzNbp7Y=,tag:luogjzi2uuvi0I1KWz+YmA==,type:str]
sops:
  age:
    - recipient: age1s0mhfvcdx5g4cfzjevfg42u9cem940txqhuetn4fhhu7dvc40g0s9tpyx7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdVpkVnA1QUNTei9QTVpC
        SHFDcXVNS3V3bDZ5WXZVVFk3Mk93VkZycjFnCm1vN05Ld1NjNHFoUGZ6Rk82UVVM
        OGY3M1djUFF2NUZWMmxIeFlVWkVjTUUKLS0tIDBialZzWTFqeGhUbG4rU1cyb2ZQ
        RlI1ME94SzhSZUxQc3VaUzhDREZTVlUK5hUkQm8sQ9b0MSc89bfqgICDFdLS7zac
        8o7hDA4rDqS2bHoi8Ny92vlHKKQZBG+PZAqHlm6Dd/XE6she5fbxJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T09:27:13Z"
  mac: ENC[AES256_GCM,data:RMEBcB11D330vdhNXeoEF1azj2IfoG/GXK8XWVmab2zUia5wEhbKdlTNRYaOUvczcJ9b5V1g154MNu+WZDoxWQfkgb1H4IwL63M1QwVTo1cwk9SAvWN+ggsZQuTjJMmhl9nJkwrTiy/kc3ESXrxRYSDvmEC4gbmZW3xkxGWBLbM=,iv:Y1P56l3f+W61RQsnUOnSM3/zpDw8BLCWZntdb5iQQLc=,tag:fW/yxiT+zpqtw1wPR0ObNg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
