---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anytype
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: anytype-secret
    template:
      data:
        AWS_ACCESS_KEY_ID: '{{ .MINIO_ACCESS_KEY }}'
        AWS_SECRET_ACCESS_KEY: '{{ .MINIO_SECRET_KEY }}'
        .env: |
          ANY_SYNC_NODE_VERSION=v0.11.1
          ANY_SYNC_FILENODE_VERSION=v0.11.1
          ANY_SYNC_COORDINATOR_VERSION=v0.9.1
          ANY_SYNC_CONSENSUSNODE_VERSION=v0.7.2
          ANY_SYNC_TOOLS_VERSION=v0.7.0

          EXTERNAL_LISTEN_HOSTS="anytype.${SECRET_DOMAIN}"

          ANY_SYNC_NODE_1_HOST=any-sync-node-1
          ANY_SYNC_NODE_1_PORT=1001
          ANY_SYNC_NODE_1_ADDRESSES=any-sync-node-1:1001
          ANY_SYNC_NODE_1_QUIC_PORT=1011
          ANY_SYNC_NODE_1_QUIC_ADDRESSES=any-sync-node-1:1011
          ANY_SYNC_NODE_1_API_SERVER_ADDR=0.0.0.0:8081
          ANY_SYNC_NODE_1_METRIC_ADDR=0.0.0.0:8001

          ANY_SYNC_NODE_2_HOST=any-sync-node-2
          ANY_SYNC_NODE_2_PORT=1002
          ANY_SYNC_NODE_2_ADDRESSES=any-sync-node-2:1002
          ANY_SYNC_NODE_2_QUIC_PORT=1012
          ANY_SYNC_NODE_2_QUIC_ADDRESSES=any-sync-node-2:1012
          ANY_SYNC_NODE_2_API_SERVER_ADDR=0.0.0.0:8082
          ANY_SYNC_NODE_2_METRIC_ADDR=0.0.0.0:8002

          ANY_SYNC_NODE_3_HOST=any-sync-node-3
          ANY_SYNC_NODE_3_PORT=1003
          ANY_SYNC_NODE_3_ADDRESSES=any-sync-node-3:1003
          ANY_SYNC_NODE_3_QUIC_PORT=1013
          ANY_SYNC_NODE_3_QUIC_ADDRESSES=any-sync-node-3:1013
          ANY_SYNC_NODE_3_API_SERVER_ADDR=0.0.0.0:8083
          ANY_SYNC_NODE_3_METRIC_ADDR=0.0.0.0:8003

          ANY_SYNC_COORDINATOR_HOST=any-sync-coordinator
          ANY_SYNC_COORDINATOR_PORT=1004
          ANY_SYNC_COORDINATOR_ADDRESSES=any-sync-coordinator:1004
          ANY_SYNC_COORDINATOR_QUIC_PORT=1014
          ANY_SYNC_COORDINATOR_QUIC_ADDRESSES=any-sync-coordinator:1014
          ANY_SYNC_COORDINATOR_METRIC_ADDR=0.0.0.0:8004
          ANY_SYNC_COORDINATOR_DEFAULT_LIMITS_SPACE_MEMBERS_READ=1000
          ANY_SYNC_COORDINATOR_DEFAULT_LIMITS_SPACE_MEMBERS_WRITE=1000
          ANY_SYNC_COORDINATOR_DEFAULT_LIMITS_SHARED_SPACES_LIMIT=1000

          ANY_SYNC_FILENODE_HOST=any-sync-filenode
          ANY_SYNC_FILENODE_PORT=1005
          ANY_SYNC_FILENODE_ADDRESSES=any-sync-filenode:1005
          ANY_SYNC_FILENODE_QUIC_PORT=1015
          ANY_SYNC_FILENODE_QUIC_ADDRESSES=any-sync-filenode:1015
          ANY_SYNC_FILENODE_METRIC_ADDR=0.0.0.0:8005
          ANY_SYNC_FILENODE_DEFAULT_LIMIT=1099511627776

          ANY_SYNC_CONSENSUSNODE_HOST=any-sync-consensusnode
          ANY_SYNC_CONSENSUSNODE_PORT=1006
          ANY_SYNC_CONSENSUSNODE_ADDRESSES=any-sync-consensusnode:1006
          ANY_SYNC_CONSENSUSNODE_QUIC_PORT=1016
          ANY_SYNC_CONSENSUSNODE_QUIC_ADDRESSES=any-sync-consensusnode:1016
          ANY_SYNC_CONSENSUSNODE_METRIC_ADDR=0.0.0.0:8006

          MONGO_1_PORT=27001
          MONGO_CONNECT=mongodb://mongo-1:27001
          MONGO_REPLICA_SET=rs0

          REDIS_HOST=redis
          REDIS_PORT=6379
          REDIS_URL="redis://redis:6379?dial_timeout=3&read_timeout=6s"
          REDIS_MAXMEMORY=256mb

          MINIO_BUCKET=anytype
          MINIO_PORT=9000
          MINIO_WEB_PORT=9001

          ANY_SYNC_DAEMONS_MEMORY_LIMIT=500M
  dataFrom:
    - extract:
        key: anytype
