---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./externalsecret.yaml
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./services.yaml

configMapGenerator:
  - name: minecraft-plugin-config
    files:
      - lifestealz-config.yml=./resources/lifestealz-config.yml
      - lifestealz-items.yml=./resources/lifestealz-items.yml
      - itemcontrol-config.yml=./resources/itemcontrol-config.yml
      - itemcontrol-limits.yml=./resources/itemcontrol-limits.yml
      - item-limiter-config.yml=./resources/item-limiter-config.yml
      - mace-config.yml=./resources/mace-config.yml
      - smputils-config.yml=./resources/smputils-config.yml
      - cartlimiter-config.yml=./resources/cartlimiter-config.yml
      - combatlog-config.yml=./resources/combatlog-config.yml
      - no-flight-in-pvp-config.yml=./resources/no-flight-in-pvp-config.yml
      - customrecipes-config.yml=./resources/customrecipes-config.yml
      - kaicore-config.yml=./resources/kaicore-config.yml
      - datapack-pack.mcmeta=./resources/datapack-pack.mcmeta
      - datapack-dragon-egg-chestplate.json=./resources/datapack-dragon-egg-chestplate.json
      - datapack-breeze-loot.json=./resources/datapack-breeze-loot.json
      - datapack-mace-recipe.json=./resources/datapack-mace-recipe.json
      - datapack-mace-damage-tag.json=./resources/datapack-mace-damage-tag.json
      - datapack-netherite-sword.json=./resources/datapack-netherite-sword.json
      - datapack-netherite-axe.json=./resources/datapack-netherite-axe.json
      - datapack-netherite-helmet.json=./resources/datapack-netherite-helmet.json
      - datapack-netherite-chestplate.json=./resources/datapack-netherite-chestplate.json
      - datapack-netherite-leggings.json=./resources/datapack-netherite-leggings.json
      - datapack-netherite-boots.json=./resources/datapack-netherite-boots.json

generatorOptions:
  disableNameSuffixHash: true
