---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: peacesmp
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  endpoints:
    - dnsName: "peace.${SECRET_DOMAIN}"
      recordType: A
      targets:
        - "${SECRET_PUBLIC_IP}"
      providerSpecific:
        - name: "external-dns.alpha.kubernetes.io/cloudflare-proxied"
          value: "false"
    - dnsName: "_minecraft._tcp.peace.${SECRET_DOMAIN}"
      recordType: SRV
      targets:
        - "0 0 25566 peace.${SECRET_DOMAIN}"
