---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appflowy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: appflowy-secret
    template:
      data:
        POSTGRES_PASSWORD: '{{ .POSTGRES_PASSWORD }}'
        APPFLOWY_DATABASE_URL: 'postgres://postgres:{{ .POSTGRES_PASSWORD }}@127.0.0.1:5432/postgres'
        APPFLOWY_WORKER_DATABASE_URL: 'postgres://postgres:{{ .POSTGRES_PASSWORD }}@127.0.0.1:5432/postgres'
        APPFLOWY_SEARCH_DATABASE_URL: 'postgres://postgres:{{ .POSTGRES_PASSWORD }}@127.0.0.1:5432/postgres'
        AI_DATABASE_URL: 'postgresql+psycopg://postgres:{{ .POSTGRES_PASSWORD }}@127.0.0.1:5432/postgres'
        DATABASE_URL: 'postgres://postgres:{{ .POSTGRES_PASSWORD }}@127.0.0.1:5432/postgres?search_path=auth'
        GOTRUE_ADMIN_EMAIL: '{{ .GOTRUE_ADMIN_EMAIL }}'
        GOTRUE_ADMIN_PASSWORD: '{{ .GOTRUE_ADMIN_PASSWORD }}'
        GOTRUE_JWT_SECRET: '{{ .GOTRUE_JWT_SECRET }}'
        APPFLOWY_GOTRUE_JWT_SECRET: '{{ .GOTRUE_JWT_SECRET }}'
        APPFLOWY_S3_ACCESS_KEY: '{{ .APPFLOWY_S3_ACCESS_KEY }}'
        APPFLOWY_S3_SECRET_KEY: '{{ .APPFLOWY_S3_SECRET_KEY }}'
  dataFrom:
    - extract:
        key: appflowy
