---
_version: 31
anticheat:
  anti-xray:
    enabled: true
    engine-mode: 2
    update-radius: 2
    use-permission: false
chunks:
  entity-per-chunk-save-limit:
    tnt_minecart: 8
entities:
  spawning:
    per-player-mob-spawns: true
game-mechanics:
  disable-end-credits: false
