apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:4DkZnuWJPSIkaVYdRoHQxQ3Q/R5XIL4SP/rp09JbiyBvFUimp6vY2s5TjdRZS7EtyOhK+Xo=,iv:JP6aWMhQ0Y6hM1p6RN8eZ4Gwgrw6QFtK7nlQg8CY27M=,tag:/cyNMWe5YnxTb22QgQMNww==,type:str]
sops:
  age:
    - recipient: age1s0mhfvcdx5g4cfzjevfg42u9cem940txqhuetn4fhhu7dvc40g0s9tpyx7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQ1puVTdhSVJ5aXYxWkt2
        dGgrN09tYkx1MGMzbFR4OUNYV0c5TkpsNFZZClpwNmR3c05rRnZlTENlbHZpcFpy
        b1I0UGxqVVNqK01PUWtEaEhmWWpUZUEKLS0tIEU2VFlpaFFQUmVLb0U1Q3MrWW1t
        UHdoVFgyZmhnam55SUZjMWkzYkQ0d00Ktaqen4xW9wq92dUos0YxcDock+F/+Jhd
        /mvjPinR3mAeqLY02/o5jMIxi6juWT6sWdKSQwVimBOqRVzg+HENLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T10:07:16Z"
  mac: ENC[AES256_GCM,data:A/1jt8E0JtRAu6DUo4xknEyQuzMexzzy8rHT1KAKEl4ZWpC9u5VgPb5GeuG2jyo07iB0oW+DGSnpdKkT6WVXqin5XeI+JUef78KK4GTyPI95XuxYhVtdtFSJEDPGLcPEffMgEMYYjraMZ35Yl3vOJKD+Z6aLQzQezmpgyDbT/UE=,iv:2ImsY3Hib9iVGdmiSkolU8PQj2G8NohzGouZKj/ZHEY=,tag:nCmMTykuAA/7ltGF+T6skQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
