apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:HyR+A7jvZyW1tYILYkw=,iv:3/ZHAJ2MlqMsrDPh+UCzwmjrsErblWVzv/TkSM054q4=,tag:vtxTbo3FPZ79/dSO8JoIbQ==,type:str]
sops:
  age:
    - recipient: age1s0mhfvcdx5g4cfzjevfg42u9cem940txqhuetn4fhhu7dvc40g0s9tpyx7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteVpoVWR5VFMzM0pFcGNn
        WnF6aVY4dWZKQW1GaExJR3lrWU9mYmhEeWdnCm9iTG1GZmcxYTFmVkpGNlV6UC9P
        Z2x6OUk3aXBMb29aaU14ejV5RHRJY1kKLS0tIGFDMktmMy9SV3JzUW9udUJrY0RI
        YkpPOTExM0NpNW94MWFxMnZ5YjNMdEUKDmIRgPWJwv4vrTWU0oM/eiay9RHHMBe9
        pmQoOTykOu0T0z+sPE1bj57pLMizoTT6KFV9GcgS+A/tUQ2lnYlFig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T10:07:16Z"
  mac: ENC[AES256_GCM,data:6p5XHeJUsDb3F+fNu8f0ffKBsifgWMQE+eHhZOpiS0Y5KdwUL9j17v6bv3HshzLzKtae3L9cRaW6eV3OYYTt5o1H3ATG6cxiK09QQtvuVXByB5/dmdl2KXWD8o4L+qqInRM/khAsLNvXQjT3lY4gbADTMppN+7m46Qoe2bUzsLU=,iv:unFbDEO9EbWyxaXBnnKA2/AVmyzJe7wzj7CAHm5G4t0=,tag:laNbpkokYNd4X1s6+42bvg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
