apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:HyR+A7jvZyW1tYILYkw=,iv:3/ZHAJ2MlqMsrDPh+UCzwmjrsErblWVzv/TkSM054q4=,tag:vtxTbo3FPZ79/dSO8JoIbQ==,type:str]
  SECRET_PUBLIC_IP: ENC[AES256_GCM,data:hGcFWfbl4OhIz46ttQ==,iv:UQd3E7b1SFyLhd/1EC4VZwssGAHDlooo9cvTEQxPzoo=,tag:mU5CMZqlFJE4spAvA7XJbg==,type:str]
sops:
  age:
    - recipient: age1s0mhfvcdx5g4cfzjevfg42u9cem940txqhuetn4fhhu7dvc40g0s9tpyx7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteVpoVWR5VFMzM0pFcGNn
        WnF6aVY4dWZKQW1GaExJR3lrWU9mYmhEeWdnCm9iTG1GZmcxYTFmVkpGNlV6UC9P
        Z2x6OUk3aXBMb29aaU14ejV5RHRJY1kKLS0tIGFDMktmMy9SV3JzUW9udUJrY0RI
        YkpPOTExM0NpNW94MWFxMnZ5YjNMdEUKDmIRgPWJwv4vrTWU0oM/eiay9RHHMBe9
        pmQoOTykOu0T0z+sPE1bj57pLMizoTT6KFV9GcgS+A/tUQ2lnYlFig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T04:33:56Z"
  mac: ENC[AES256_GCM,data:5yud4jvABN+bjHwwnwve9acetz7tg3oA6Hvhi0XpqwugP2qPTIN2W/k9y+NIrhDwD3N8RuRpHQf+bh/IM6fIPPXAduXNePIL/eIX/80TxWlK1u7Q8JXBRK1uiXTWUOQRGmLs5bCt9qRiV/VmW2QZ9Eo/71vQRJK/afECzHY7Y4M=,iv:6Sbyd0vC6/kZb+h+hMRnU/RI1PcFLNdyCQVgEERdV84=,tag:VfsWT4/AOM5bNOeBXCpsoQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
