---
apiVersion: v1
kind: Service
metadata:
  name: omarchy-vnc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: omarchy
  ports:
    - name: vnc
      port: 5900
      protocol: TCP
      targetPort: 5901
