apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:yXn44d2UxBUnqaGMJsMD2Bst0NN0qAop79JAKtdcuy0=,iv:ZGAW3x6kCU1j9/AzCkYmtopI7gyZMN3k2QcCj2b/IGs=,tag:VuFrkjKV8/CmJSPa4wub+A==,type:str]
sops:
  age:
    - recipient: age1s0mhfvcdx5g4cfzjevfg42u9cem940txqhuetn4fhhu7dvc40g0s9tpyx7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUHFVd0lrWUxTa2V0ejM3
        QUp3bzBKY2JueWFXSFZUaWRJdWEyb2FrUVN3ClE0N00vV2xmUDBLb1NrVSt0eHlP
        dzZldjBLT2xZUVlIT0JiYnB2TzU0eFEKLS0tIFJhRkV5bXMzSXRwV0I4cDN5ZWhU
        UXNnQlRpT2lqdWoySXBoa3U1eWpTbmsKhNudX3XGmyH0W89IjHfgWogJToLM8BGL
        25i7gs2mPUgVHIk+6r1wkAAMQ0PXt6EuffGgqfWLMyNsr5/AX3Pt+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T10:07:16Z"
  mac: ENC[AES256_GCM,data:ZLdWScENuCWUK6LK6h3dDTaQ7L3yjMeZgC57gTcgbXkhLH/9fmMCvORqQx+gbY7MZGSXa5VrkcOvIITwzIVlSrgjmq7+UiGdcdHOvjxWXGuP68R77FshQ5mbTVzHo33iSFJZTeyONicDraH+UvAcSGHf4JMnYqTIgdDHvz1lTRM=,iv:9/d31aK94/pLelBD+aVbQ8Ylxm4VUPKTFMc15rb42LU=,tag:kr4T35Zf4+AwgS+VPDalXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
