---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/config-map_v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-config
data:
  librechat.yaml: |
    version: 1.3.13
    cache: true
    interface:
      modelSelect: true
      parameters: true
      presets: true
      prompts:
        use: true
        create: true
      bookmarks: true
      multiConvo: true
      fileSearch: false
