---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: librechat-secret
    template:
      data:
        CREDS_KEY: "{{ .CREDS_KEY }}"
        CREDS_IV: "{{ .CREDS_IV }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        JWT_REFRESH_SECRET: "{{ .JWT_REFRESH_SECRET }}"
        MONGO_INITDB_ROOT_USERNAME: "{{ .MONGO_USERNAME }}"
        MONGO_INITDB_ROOT_PASSWORD: "{{ .MONGO_PASSWORD }}"
        MONGO_URI: "mongodb://{{ .MONGO_USERNAME }}:{{ .MONGO_PASSWORD }}@librechat-mongodb:27017/LibreChat?authSource=admin"
  data:
    - secretKey: CREDS_KEY
      remoteRef:
        key: librechat
        property: CREDS_KEY
    - secretKey: CREDS_IV
      remoteRef:
        key: librechat
        property: CREDS_IV
    - secretKey: JWT_SECRET
      remoteRef:
        key: librechat
        property: JWT_SECRET
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: librechat
        property: JWT_REFRESH_SECRET
    - secretKey: MONGO_USERNAME
      remoteRef:
        key: librechat
        property: MONGO_USERNAME
    - secretKey: MONGO_PASSWORD
      remoteRef:
        key: librechat
        property: MONGO_PASSWORD
