apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: observability
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:kjU9vbzDvmmCfX1Qbu536w==,iv:vT9b9RW5iNhSb6KR0buW2p9lPhXSKbiBm009AVtuOZk=,tag:WQbyEfd2AQCbz8eScmxGYw==,type:str]
sops:
  age:
    - recipient: age1kcam3zk2y8f6cjv0f0mxkpe0w538mm4rnelr4g42xlcwskyqugeqffjlss
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoai9nMDhWYTBRd1UwRzhU
        bmUvcU5lMkpUb2lOQ25lTXQrS2N4d01OVUM0CjNTWVh4NTFlS3czbUdBWVhqUkl3
        cmNUOVRINlp3WEFPbHZkU3dETkQ2dzgKLS0tIFFHUms4dE5iZStKVEtDdFBPQzJu
        NkVsNFpRU2c1L0g1ZzBJbjFQK1ZOUXcK2BfGHTGejljgzaysn2Zq5xsWabKWtR8+
        K7jYuKBog0hVH2rYX2iGxlf+pthsPFDHCQctHLZUC5fgWp4hQIRAGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T08:48:09Z"
  mac: ENC[AES256_GCM,data:PG3TA3nfc52eY83bzmGusxYk+jp7jrxx0nEAaWIDjRN9B+NFFIe4R6jUlhwLhu0cW3OsA1KBXi+4veugpk+mOGKJG2QiKGyJgOKU1laICXOpZxVEKyQ3qKL9x+rQANfHxWoKTybufoLBMHlataNU1LPvXAvaPf05DDT82frFW4E=,iv:XYpsqVsJDg58skc4CJC6MxTcAe/zl8JExY+WIAOcVNw=,tag:hxmFtHN5/FdXcPvEKme4Wg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
