apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: observability
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:bRCMWxhVIl9lks8MOEAnXTIyoCyTXpnzKMkQiQV/rZE=,iv:1u53LgfYEAfpI2SB7YviClyE7DYg2rPL5oM9+7lwK9g=,tag:XAtbRMHFeFMHVLkXai+AOA==,type:str]
sops:
  age:
    - recipient: age1s0mhfvcdx5g4cfzjevfg42u9cem940txqhuetn4fhhu7dvc40g0s9tpyx7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUm9DZU9za3hXeVE1TDlm
        TFZGUmJZb2lrSG0xcU14akltQjFYa21jUDBnCjlZdlhQRWU4cm5aZ1N1Skl5N00y
        ZWZpUUhLdTlWVi9kR2RvWklGSTltbzgKLS0tIFAyWFR2alR3cmczQUlmT0FkTFF1
        N3ZhK3l2VFN6Y1gzeEVhWUVnUlUzRE0KIU5rQzyHLCGiIB9rjsaQxTDt9h2Askp+
        AD40Ms0t728yXezSG0fQwyn9mQ1pOwt3JBDK0xYR8qELyILzHv7yBA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T01:21:16Z"
  mac: ENC[AES256_GCM,data:FDX8IiI9kFBTHcxJdkWWZ8XqPvtejMocjVMj8CQj1GfI+cwK4Iaveg8Qz/eWJ3mNUnc+8aUFSkiJU4COp0QBUobcfDwCzATTi1IvMX90tHFxsR19dLEvEuzky/PZurT0KAqmNQskbgy2vhQJkiUZ0Z7suVHq2OaagKw7mbFiPxQ=,iv:3RGhVnnh0cMvQ820e2rKSzCq7u+XY88sKsiTDvTX/LE=,tag:sqoabhM8lfOmVxKho6u4Jw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
