---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cli-proxy-api
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cli-proxy-api-secret
    template:
      data:
        config.yaml: |
          host: "0.0.0.0"
          port: 8317

          tls:
            enable: false

          remote-management:
            allow-remote: true
            secret-key: "{{ .MANAGEMENT_SECRET_KEY }}"
            disable-control-panel: false
            disable-auto-update-panel: false

          auth-dir: "/data/auth"

          api-keys:
            - "{{ .API_KEY }}"

          logging-to-file: false
          redis-usage-queue-retention-seconds: 60
          ws-auth: true

          openai-compatibility:
            - name: DGX Sparks
              base-url: http://192.168.20.21:8888/v1
              models:
                - name: deepseek-v4-flash-vision-exp

          oauth-model-alias:
            codex:
              - name: "gpt-5.6-sol"
                alias: "codex-gpt-5.6-sol"
  dataFrom:
    - extract:
        key: cliproxyapi
