apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:4KnDFz20Wv1lc3mmsX7o2rgecmP/Gx3KKxRR4h2pNaRjdS/ON/51VV36FjP7L/qxbbvteuDaifZQWGJLxoFCY9lsTiNeHtRed7eU9ov2o5fhVHwbUA7xx9GcgFJ7xMG7472RYJ7cA2EVvIntSpoaDwA3vUHTJBoMCxeBKMBi8BdGREIr9gTN1Ms26u05fCLkZfPcKCQ4AXktDDpoxgWPpUlaIyWU++3e9ApOG5xIuQyGCvJR,iv:R7hApaBzkAtgQ8ElusR2ltRekH0+w4KfNEmmJCMbkSM=,tag:SxFKmowYRuYxgPmmLXFOeQ==,type:str]
sops:
  age:
    - recipient: age1s0mhfvcdx5g4cfzjevfg42u9cem940txqhuetn4fhhu7dvc40g0s9tpyx7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NE9ib0N3ZVRDSHhpdzhS
        RW5kVVNMWGxNN1IyVFp5d2xqU2pvVE9HTW5ZClpZMFoyMWpKZWg0OFY5bmZXZjRY
        SkhycS81YXVSbFBIazNVQ1FlYmlsNEUKLS0tIGt1ZXMvWkpMZEdBTXlOVldiNzNu
        bnFZTWVQUTJ3K2JQVFNqNVFCT2c0bUEKxSwuK15adqMoipScd6ixm8ilhSV2p2DF
        2TGdfzd/v4WyObrvBFmSA/NASEfJ0RoQNwZouztgYTFSXvj8JDLCTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T10:07:16Z"
  mac: ENC[AES256_GCM,data:O73cEE6fElYaE2XdRC5NIvHe/48qqJ3H3I5fJgDdYz4QYY822+mH0mZFy1C4oh/XS/Fs4oaWb9a6fLdgxNqUkV+sXkoTzV55i5X5E9rvxyeokEpV2yR0+dqIptTQm4knEHav99pGGi5DskFFAaqvBkg1GkjZZnsT3F6BD0T9AwE=,iv:K7yZiXHxBPfWZbWbS0ug4mJE/YSMVp6WQqStFZwF+C0=,tag:g+sDYaj8S2T3xsr3An5xeA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
