apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-credentials-secret
stringData:
  1password-credentials.json: ENC[AES256_GCM,data:d04vOgMT45jI4uvc6YTyRaGjt8s7YfTE3uQe/PBVVJ2ssjLZtFtoD236fps1OKOCglJKMatWcRLR+b/QlEYaLJj+fjuZE5FYG5DAigxE845JxWC6INW77WbHBeBG6puLJUF943+TVtKX/klqpGoIZPnsZhuTUlZMhHfwVJt2QPa1fYO4IMCiED3DVs56oC4zxEriTpI2JbQZvKAOkA5frOD+kL8ll5fQs8skAeL/u/e1sxRdcZ9CxL7Fy3CxIU6TG+Sv6Z/Jwvcu8Z0JQE9V7Rl8DLeauq2qTXH4JFQMmTQ+x566B2yvo8SdoDYAqOiEUEXgW/A9iMKW3lXrKXWd/AqT57eeWn1vgubH3M7piKjR3qYlpsarifu6XDAgGERMi0EOym+jsrjDZWsiU4LUdvzIggEgUl7SSc1XMKqcW2uwjOPVRuBzFeEBQGsJHDEj6b8xcRf24qJRxDfVdQbJLcwTJ+k8YWpUcSW6TzVHvKsNonirITPXw+czWa9LoWIWAVNWRsAZyW8OhBYI2BpYGD6CChwzal7cUoAAsRqJPg1u7VQ5OYHKrjTMFklgRAWaONixoopGBBUut6zK2h6p6e/s85ZepRJ9ZpThqrE2bl+bSFpz7FUSvfxT7Gw6ku16CyzCzzRbqPRDfXRuenEd4VIKqC0pigAILgBUcF9I1rfb1OsKxngt8XY+gzAFRgj2seHMDWe7dvOVOauCfk6MBzf8ucsULSEK85PMga3IdMAz0N7ukReJSBIYmToO3h4wHM2qhYyj6c3b2nucghH7/jpZZHm35nk13YiSRoDfcDjJURLV9TLcfWCze78yoWRgl1+QO7RMLZSuwpXBvtfYkqyQMOjwm3Vab2bF6tC37SX6knwpqqZv8JSAATbrk4M/JXLAMrmB8iqDn5Et3sK+zmYRs05QT5nFe4LSF9nuIx6KMPSZVI3bW4/goZladEUDetNuzxI3MSX2DD6iXm8wjl/GVy9Y1Ee1wMEerX4a9vMBx3M4Le6eFgMgyH9RZO/AOdl2MJ2VS4YHkU0xjkkpnvaO2jblhaaHUrafg2C+D1BSYPQPYsKc31HkClhnyLWBwmLHuY7zMG6HtXWV9BaPV92PMnmgpPoQYyw4xK/fQdoiTFzmlHcEK2LMRVJSm0VR1pGcWJkc1pIMHJRgLG0WvCAyozaL/cVklRFvGGFrfwT4wGJp3bEiP7YLELHmYGqLKhp4tSTjsXmnq0CFbDHOp+FcdTgkIRPRUSBwAxsho667eoESj8fHcq2Hhb57r0MIG16ZHrgqNErxtu6RsLUZlg/BShB3L6ZG1qOj2wzJcXreKw4HbcRq6PezZTW2mQTgFJu0CHGRfJzwqPaFxJYFe2HkHU71PvTFk31w1XaI/y3MdDXbkkTW+2bxCDPvPfDA474uVWwl8NZTLgCDoIdm2fr0H+BvIkE3lISehNFmoQ==,iv:9gebZFcGZuz0o7P0Ey+KchUE6vL+0qUG2xFz36KZBsk=,tag:GUDx2mm4YNjaHlVGKmhZdA==,type:str]
sops:
  age:
    - recipient: age1s0mhfvcdx5g4cfzjevfg42u9cem940txqhuetn4fhhu7dvc40g0s9tpyx7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UTA1Y0RLUkhNUmkrbVBp
        L2RHWWN1b3IrWHQzdWsvbDlyK2VYYlMwMWxnCkREaXhYV0E1VjRxa3BETHNzSStH
        OEIyNG9qblR0Y1NyV1pnejZUR3NOb1UKLS0tIEdvQjBMaERhLytRd2Z2eTQ5REpN
        cjRMdVJFWlJEaDZERzlvU2pmbyt5WGcKZeQ0PUCWRLhAEifHV5QjeQNVjo/dHgTa
        JR97s32zU87TRaimwIIuETXvl3jgn4m/BzTJM0tL337EzvzIhfSkRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T10:42:05Z"
  mac: ENC[AES256_GCM,data:LzhOUOxKWS2v7TqqrCLG9YnIGh52jikELYQ8B503pZOVfp+is219HyKx/GM9+eBJHuHFu9BK0pS8cQ8Y/uGdm1EDVyMwtdL4XZJ6yVWNkEkOEFuLgTLgyKkAQfi7PZjsfAzmwV6dUu3JMrMFpqQQqt1V5e/P6bz72/1syB0vmdM=,iv:RGcgHNyBVwE/neasGi29/3vnJgzBL61fB5Kdbr3SYoE=,tag:Oet00e0Igoj01EjRVvDguQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-vault-secret
stringData:
  token: ENC[AES256_GCM,data:ysrasAHh4sauEKSwWJeweMv6aXmcAH97zHW939WJU4yC9E6HVxcowf6dQBP+Zl53AHZqZa3nTx6vg5Q/xGTcf5sUCrY1WYEunAz15Bg2E9/k24Cwq4uCdYJ7ikhOVaROcCwLOHEvrIydK3E9GI0TKmOStl7QlvCzlMTmk0w2lcjPQglcNgci+/JdippYhHJfnVbgH9lVqaca5OtpjCnPYo5F1maged1fuodhLkZ78Qme5V0p/lmZAgA7r9WeKMms/FXQKPbk/+9lrz4OzF4pGfz5yibHTLVfcyYg2WPHsSkjrLo11MRtxpoM3irKXVbtgnHWfbPSQVsjy4rCrF+fU903+lOU2fZwLv29G31EzPMIJ2uaIbm1glOG9OXbG27PvDgR8FZ0ZVBxtPOqu5bmEaWDxu1JjCTKl+LDvz3CpZxvmZ3aAd3zwwiN3x4KluR9KFdC5bsU95pjNup3l8xLHtm2Hb/aNTrOWIEU08n52YLtWCmsGbwVEQsaAW1x5/NNqQE7w01ukGPejtLgw9ezWquynZdymeUpn1G9llGTJm2G3KXydM7m8wuOjkGAXFevHNofgpU+2GYDl/+wb4wbjBs2s3vJ6spyF+YpLCgq5n7eixUhTiQXYgCEqSHCoQVfdOF8tb7IjINbDeWtit+3EloyvdWuoybiWYAHGeCiJ+QoIDfYNhPPJhZ7l+URc+df3lda9QLRhDfBTOSBIaFrA7TTzceNsLSEIRwMKr8svTnXDpZrTZezA/tuzf1cHHa7hK9mpY0kAhpighYhwCDpBGYnuYGw+dVSRUPcmDKEAiRXoyQvxBt81a/ngnOzA1gf0vjqB60hXY37Cpfq6OXbsuLF,iv:oXEReQeaN+sfWvIsSJIgljxqcPwP1/WE4+OFThnYweM=,tag:G0H7MBkTBa5t2pKIAJ7shw==,type:str]
sops:
  age:
    - recipient: age1s0mhfvcdx5g4cfzjevfg42u9cem940txqhuetn4fhhu7dvc40g0s9tpyx7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UTA1Y0RLUkhNUmkrbVBp
        L2RHWWN1b3IrWHQzdWsvbDlyK2VYYlMwMWxnCkREaXhYV0E1VjRxa3BETHNzSStH
        OEIyNG9qblR0Y1NyV1pnejZUR3NOb1UKLS0tIEdvQjBMaERhLytRd2Z2eTQ5REpN
        cjRMdVJFWlJEaDZERzlvU2pmbyt5WGcKZeQ0PUCWRLhAEifHV5QjeQNVjo/dHgTa
        JR97s32zU87TRaimwIIuETXvl3jgn4m/BzTJM0tL337EzvzIhfSkRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T10:42:05Z"
  mac: ENC[AES256_GCM,data:LzhOUOxKWS2v7TqqrCLG9YnIGh52jikELYQ8B503pZOVfp+is219HyKx/GM9+eBJHuHFu9BK0pS8cQ8Y/uGdm1EDVyMwtdL4XZJ6yVWNkEkOEFuLgTLgyKkAQfi7PZjsfAzmwV6dUu3JMrMFpqQQqt1V5e/P6bz72/1syB0vmdM=,iv:RGcgHNyBVwE/neasGi29/3vnJgzBL61fB5Kdbr3SYoE=,tag:Oet00e0Igoj01EjRVvDguQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
