---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./cliproxyapi/ks.yaml
  - ./hermes/ks.yaml
  - ./librechat/ks.yaml
