---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.35.2-standalone-strict/_definitions.json
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
spec: {}
