---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./glance/ks.yaml
  - ./forgejo/ks.yaml
  - ./appflowy/ks.yaml
  - ./anytype/ks.yaml
  - ./searxng/ks.yaml
