apiVersion: v1
kind: Secret
metadata:
  name: external-dns-unifi-secret
stringData:
  api-key: ENC[AES256_GCM,data:aYYrg4UnQpwyYyifpZLWsVwuRux9M9aXz84zDZLZzmg=,iv:HYA0/iBvIhFvaI966Rpyh6qZ7HP8QEIx3FdIM1P3bRA=,tag:+klQsT1yljoFefYeNxGsaA==,type:str]
sops:
  age:
    - recipient: age1s0mhfvcdx5g4cfzjevfg42u9cem940txqhuetn4fhhu7dvc40g0s9tpyx7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNHJsZWJtaVA2RVdzUEMv
        QkszWmtQT1FiMGVHaWE5UUtQRlArbWZhVjA0CnEycmw2bFFDcTFmMVRFcnNJMStT
        T0ZTK2ppVHpMZ0tkUmFVQ1pzbTJBWEEKLS0tIFVHanVDU3VaVmNTRk1FY3lwck5U
        bXc3U1lKNEVxNXpSdEtva0h5UWt1dUkKsvhPW51KGBI5xMdxlI48JiTG4tx+HQ5N
        zF1XnLv98NAUQECo9MoKaTGQJMxJceM2Tl6ReckYiXKPmhl1CbZWaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-06T10:05:03Z"
  mac: ENC[AES256_GCM,data:KnxgiOJmjvumA5TaPPxzZ24SJhzf4Rt6/lNFySw64Cd65xUtPTYDEK3FfqEwKUAoTtI9hTn5MJ5QL2yldVwWD7bmVAy3P+2wuKJsONm03atdaZd98hjw3IjLr9buNTpMhFcTQ+WXB/dwWX7cof7kz0dZw9RfyXtVKtEyaEaH2cY=,iv:s4tUWdqEbz7HwLQGLnycJhZz8Shh52A9nJY6HYBfEE8=,tag:njY8qWLiNQVnpcDDTO4xyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
