apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Wvt6qmC/pryiUTRyoK+NiJPTJ3BdjZ7oIK54JHcNheUhZNKF9gvYvz73h4SlnKaDCsC+rTI=,iv:5GJuK9CPIz8mZQAD2LihgxXvdMh2xFC5q48yqiVa5GE=,tag:K4pRUnNATgd+3vE5bKfgbw==,type:str]
sops:
  age:
    - recipient: age1s0mhfvcdx5g4cfzjevfg42u9cem940txqhuetn4fhhu7dvc40g0s9tpyx7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLanFYR1dmR1NQRTNacmJ0
        NUZYMHpzYzlZZGpyZUxMdUVVUm9OUDRaTDFrCkEwWjcwYmxPNDYvT0NmV2s1UEhy
        UEpPOEFlM3hienViVEhHMFR3cXRONGsKLS0tIHl1aDgzM3JhRzNPcjIyK29iYnVm
        bFNFbk1qRWgzM1ZmRUx6RGg5NzRycncKpKV5HohsaGYLUCD+hj3g1g4nvh7OfiLr
        l1sx9zwPWNTxWQo9CTMKSxLMZHF16USHZEKGVyaWgNHnCRUP5cmnbQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T10:07:16Z"
  mac: ENC[AES256_GCM,data:641zOFSk420icEU1ZTZRjG6W6/DtY4YarfMVG+PS+4ypNx5xky8u2tMJa2fIZWjOzWybPXIzmJqWj6NzMK5XybFeZ6DtAs8mRLpFEwHCxhVBX3FZ6nr/DMvHiwBiYzdHTnIQIfb7NU1e5HrCP+U6JrxBNmks/Ww50iF2h/EGqJM=,iv:idoKt29e729VeMrmAkyZlI/ClNAj3poal7ZP/QGc92k=,tag:/1hu9WgqKwpXcOv2h3FhXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
