---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.20.100:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.20.100"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "ms-02-ultra"
    ipAddress: "192.168.20.10"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/b7702dcc9325d40db023b174e7afce05fa626558850701db8658572357135058
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "38:05:25:35:44:49"
        dhcp: false
        addresses:
          - "192.168.20.10/24"
        routes:
          - gateway: "192.168.20.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.20.100"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

