---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hermes-secret
    template:
      data:
        HERMES_DASHBOARD_BASIC_AUTH_USERNAME: "{{ .DASHBOARD_USERNAME }}"
        HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: "{{ .DASHBOARD_PASSWORD }}"
        HERMES_DASHBOARD_BASIC_AUTH_SECRET: "{{ .DASHBOARD_SECRET }}"
        API_SERVER_KEY: "{{ .API_SERVER_KEY }}"
        OPENAI_API_KEY: "{{ .API_KEY }}"
  data:
    - secretKey: DASHBOARD_USERNAME
      remoteRef:
        key: hermes
        property: DASHBOARD_USERNAME
    - secretKey: DASHBOARD_PASSWORD
      remoteRef:
        key: hermes
        property: DASHBOARD_PASSWORD
    - secretKey: DASHBOARD_SECRET
      remoteRef:
        key: hermes
        property: DASHBOARD_SECRET
    - secretKey: API_SERVER_KEY
      remoteRef:
        key: hermes
        property: API_SERVER_KEY
    - secretKey: API_KEY
      remoteRef:
        key: cliproxyapi
        property: API_KEY
