---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: searxng-secret
  data:
    - secretKey: SEARXNG_SECRET
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword-connect
      remoteRef:
        key: searxng
        property: SEARXNG_SECRET
