settings:
  notify-player: true
  notify-message: "&9&lMax limit for &b&l{item} &9&lis &b&l{limit}&9&l."
  banned-message: "&cThis item is banned on this server."
  drop-excess: true
  sweep-interval-ticks: 20

limits:
  GOLDEN_APPLE: 128
  ENCHANTED_GOLDEN_APPLE: 0
  TOTEM_OF_UNDYING: 0
  ENDER_PEARL: 0
  END_CRYSTAL: 0
  RESPAWN_ANCHOR: 0
  TIPPED_ARROW: 0
  COBWEB: 128
  EXPERIENCE_BOTTLE: 192
  BREEZE_ROD: 64

  POTION_HEALING: 6
  POTION_REGENERATION: -1
  POTION_STRENGTH: -1
  POTION_SPEED: 0
  POTION_FIRE_RESISTANCE: -1
  POTION_INVISIBILITY: -1
  POTION_SLOWNESS: 0
  POTION_WEAKNESS: 0
  POTION_POISON: 0
  POTION_RESISTANCE: 0
  POTION_SLOW_FALLING: 0
