checkForUpdates: false
lang: en-US

startHearts: 10
maxHearts: 20
reviveHearts: 1
heartsPerKill: 1
heartsPerNaturalDeath: 1
minHearts: 3
enforceMaxHeartsOnAdminCommands: false
heartItem:
  default: defaultheart
  withdraw: defaultheart
  kill: defaultheart
  naturalDeath: defaultheart
  heartGainCooldown: defaultheart
  maxHearts: defaultheart

dropHeartsPlayer: false
dropHeartsNatural: true
dropHeartsIfMax: true
looseHeartsToNature: true
looseHeartsToPlayer: true
announceElimination: true
allowDyingFromWithdraw: true
minWithdrawHearts: 0
healOnHeartUse: false
playTotemEffect: false
heartCooldown: 0
maxRevives: -1

preventTotems: true
preventCrystalPVP: true
preventRespawnAnchors: true
preventBeds: true
preventCustomItemsInItemFrames: true

disablePlayerBanOnElimination: true
heartRewardOnElimination: true
eliminationCommands: []
heartuseCommands: []
reviveuseCommands: []
reviveStartCommands: []
showBossbar: false
bossbarColor: RED
bossbarStyle: SOLID

gracePeriod:
  enabled: true
  duration: 3600
  announce: true
  playSound: true
  damageFromPlayers: false
  damageToPlayers: false
  useHearts: false
  looseHearts: false
  gainHearts: false
  allowWithdraw: false
  startCommands: []
  endCommands: []

bypassPermission:
  enabled: false
  damageFromPlayers: false
  damageToPlayers: false
  useHearts: false
  looseHearts: false
  gainHearts: false

heartGainCooldown:
  enabled: false
  cooldown: 120000
  dropOnCooldown: true
  preventPickup: true

antiAlt:
  enabled: false
  logAttempt: false
  preventKill: false
  sendMessage: false
  commands: []

webhook:
  elimination: false
  revive: false
  url: ""
