defaultheart:
  name: "&cHeart"
  lore:
    - "&7Rightclick to use"
  material: NETHER_STAR
  enchanted: false
  customModelId: 0
  customItemType: heart
  customHeartValue: 1
  minHearts: 0
  maxHearts: 10
  requirePermission: false
  craftable: true
  recipes:
    1:
      rowOne:
        - GOLD_BLOCK
        - GOLD_BLOCK
        - GOLD_BLOCK
      rowTwo:
        - OBSIDIAN
        - NETHER_STAR
        - OBSIDIAN
      rowThree:
        - DIAMOND_BLOCK
        - DIAMOND_BLOCK
        - DIAMOND_BLOCK
  invulnerable: false
  despawnable: true
  whitelistedWorlds: []
  sound:
    enabled: true
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1.0
    pitch: 1.0

revive:
  name: "&cRevive Beacon"
  lore:
    - "&7Place down to use"
  material: BEACON
  enchanted: true
  customModelId: 0
  customItemType: revivebeacon
  reviveTime: 30
  allowBreakingBeaconWhileReviving: true
  decoyMaterial: RED_STAINED_GLASS
  showEnchantParticles: true
  showLaser: true
  innerLaserMaterial: RED_GLAZED_TERRACOTTA
  outerLaserMaterial: RED_STAINED_GLASS
  showParticleRing: true
  particleColor: RED
  requirePermission: false
  craftable: true
  recipes:
    1:
      rowOne:
        - DIAMOND
        - BEACON
        - DIAMOND
      rowTwo:
        - OBSIDIAN
        - defaultheart
        - OBSIDIAN
      rowThree:
        - DIAMOND
        - BEACON
        - DIAMOND
  invulnerable: false
  despawnable: true
  whitelistedWorlds: []
  sound:
    enabled: false
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1.0
    pitch: 1.0
