apiVersion: v1
kind: Secret
metadata:
  name: openclaw-secret
stringData:
  OPENCLAW_LOG_LEVEL: ENC[AES256_GCM,data:s2QkxQ==,iv:bAi/1EXUjCfGfFip3Ym5BBVtR10Ah9tHvT+L9vaKf7g=,tag:359Kuw8YL2zYNqn6McODSg==,type:str]
  OPENCLAW_GATEWAY_PORT: ENC[AES256_GCM,data:VWITZYA=,iv:JAQ80A8xvgSjXDACQ0HNLL/aU9sWfDtavnQuNU3uQj0=,tag:EiVJQAdtGu++3tebZMLidQ==,type:str]
  BROWSER_WS_ENDPOINT: ""
sops:
  age:
    - recipient: age1s0mhfvcdx5g4cfzjevfg42u9cem940txqhuetn4fhhu7dvc40g0s9tpyx7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMXRyS3JtUThIQlJta3h6
        STJ6Vnh2STlLRXZTK3k1NVM0R20yeWpiZ3dVCkRHSWNyRXdpcUlBakFCWFFVSHhT
        Nkk2bTl4cmZiSlRnaExMUGFOenhKZjAKLS0tIEZCUThPay82dE1YVkdsTWluUWpM
        SnFrQWRsN2NXN0hueHcxWnN2eEpoVXMK0DjeD7hLgbmVwdGHT+RSSGCcpx3hSRq9
        8cq2TYxjLP2jTDDZ4seOiuFLRo/8O7FkPR+lOCs1uRnCFZEJrRIxAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T23:33:14Z"
  mac: ENC[AES256_GCM,data:Hcfi5K74U3XOK9vjGHIXnoHt0uT9nNUc1rvGYBRlTth46KLpl54qMHj4JawIAD+eP97w/ELKNGMq+5M9rUO77tEpdI3D8l5CFhoSHSWgMqZOue8Agry9ZV2oHx968oRx6ED9jpat5pHtxQc7VqoEhz6Ge1v90mbNPKjAJriBulk=,iv:/m6NFu6WJYH9ZZy1SXsDB4X/03aHlGwdcty+Pmuq+jo=,tag:Z9yqsn9ErEpdVmcT4qDoQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
