---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./app/dnsendpoint.yaml
  - ./app/helmrelease.yaml
  - ./app/ocirepository.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: glitg-smp-spawn-protection
    files:
      - config.yml=config/plugins/SpawnProtection/config.yml
  - name: glitg-smp-patches
    files:
      - glitg-smp.json=config/patches/glitg-smp.json
  - name: glitg-smp-doublebreezerods
    files:
      - pack.mcmeta=config/datapacks/DoubleBreezeRods/pack.mcmeta
      - breeze.json=config/datapacks/DoubleBreezeRods/data/doublebreezerods/loot_table/entities/breeze.json
  - name: glitg-smp-eightminutestrength
    files:
      - pack.mcmeta=config/datapacks/EightMinuteStrength/pack.mcmeta
      - consume_strong_strength.json=config/datapacks/EightMinuteStrength/data/eightminutestrength/advancement/consume_strong_strength.json
      - extend_strength.mcfunction=config/datapacks/EightMinuteStrength/data/eightminutestrength/function/extend_strength.mcfunction
