---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./app/dnsendpoint.yaml
  - ./app/helmrelease.yaml
  - ./app/ocirepository.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: glitg-smp-paper-world-defaults
    files:
      - paper-world-defaults.yml=config/config/paper-world-defaults.yml
  - name: glitg-smp-server-icon
    files:
      - server-icon.png=config/server-icon.png
  - name: glitg-smp-spawn-protection
    files:
      - config.yml=config/plugins/SpawnProtection/config.yml
  - name: glitg-smp-lifestealz
    files:
      - config.yml=config/plugins/LifeStealZ/config.yml
      - items.yml=config/plugins/LifeStealZ/items.yml
      - storage.yml=config/plugins/LifeStealZ/storage.yml
  - name: glitg-smp-kaicore
    files:
      - config.yml=config/plugins/KaiCore/config.yml
  - name: glitg-smp-grace999
    files:
      - config.yml=config/plugins/GracePlugin/config.yml
      - grace.yml=config/plugins/GracePlugin/grace.yml
  - name: glitg-smp-cartlimiter
    files:
      - config.yml=config/plugins/CartLimiter/config.yml
  - name: glitg-smp-slashstring
    files:
      - config.yml=config/plugins/SlashString/config.yml
  - name: glitg-smp-itemcontrol
    files:
      - config.yml=config/plugins/ItemControl/config.yml
      - limits.yml=config/plugins/ItemControl/limits.yml
  - name: glitg-smp-coreprotect
    files:
      - config.yml=config/plugins/CoreProtect/config.yml
  - name: glitg-smp-grim
    files:
      - config.yml=config/plugins/GrimAC/config.yml
      - database.yml=config/plugins/GrimAC/database.yml
      - discord.yml=config/plugins/GrimAC/discord.yml
      - messages.yml=config/plugins/GrimAC/messages.yml
      - punishments.yml=config/plugins/GrimAC/punishments.yml
  - name: glitg-smp-invsee
    files:
      - config.yml=config/plugins/InvSeePlusPlus/config.yml
  - name: glitg-smp-bukkitofutils
    files:
      - base-config.yml=config/plugins/BukkitOfUtils/base-config.yml
  - name: glitg-smp-doublebreezerods
    files:
      - pack.mcmeta=config/datapacks/DoubleBreezeRods/pack.mcmeta
      - breeze.json=config/datapacks/DoubleBreezeRods/data/doublebreezerods/loot_table/entities/breeze.json
  - name: glitg-smp-eightminutestrength
    files:
      - pack.mcmeta=config/datapacks/EightMinuteStrength/pack.mcmeta
      - consume_strong_strength.json=config/datapacks/EightMinuteStrength/data/eightminutestrength/advancement/consume_strong_strength.json
      - extend_strength.mcfunction=config/datapacks/EightMinuteStrength/data/eightminutestrength/function/extend_strength.mcfunction
