---
name: GLITG SMP Image

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/glitg-smp-image.yaml
      - smprules/**
      - kubernetes/apps/games/glitg-smp/config/**
      - kubernetes/apps/games/glitg-smp/image/**
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: kubernetes/apps/games/glitg-smp/image/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/glitg-smp:2.0.2
