---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.3/helmrelease_v2.json?values=forgejo/17.1.0
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: forgejo
  install:
    timeout: 10m
    remediation:
      retries: 1
  upgrade:
    timeout: 10m
    remediation:
      retries: 1
  values:
    image:
      rootless: true

    strategy:
      type: Recreate

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 2Gi

    persistence:
      enabled: true
      create: true
      mount: true
      size: 20Gi
      accessModes:
        - ReadWriteOnce

    service:
      http:
        type: ClusterIP
        port: &port 3000
      ssh:
        type: ClusterIP

    httpRoute:
      enabled: true
      annotations:
        gatus.home-operations.com/endpoint: |-
          group: external
      parentRefs:
        - name: envoy-external
          namespace: network
          sectionName: https
      hostnames:
        - git.${SECRET_DOMAIN}
      matches:
        path:
          type: PathPrefix
          value: /
      port: *port
      terminate: true

    tcpRoute:
      enabled: false

    test:
      enabled: false

    gitea:
      admin:
        existingSecret: forgejo-admin-secret
        email: strxnd@users.noreply.${SECRET_DOMAIN}
        passwordMode: initialOnlyRequireReset

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

      config:
        APP_NAME: strxnd Git
        RUN_MODE: prod

        server:
          DOMAIN: git.${SECRET_DOMAIN}
          ROOT_URL: https://git.${SECRET_DOMAIN}/
          PROTOCOL: http
          HTTP_PORT: *port
          DISABLE_SSH: true
          START_SSH_SERVER: false
          LFS_START_SERVER: true

        security:
          INSTALL_LOCK: true

        service:
          DISABLE_REGISTRATION: true
          REQUIRE_SIGNIN_VIEW: false
          DEFAULT_KEEP_EMAIL_PRIVATE: true
          DEFAULT_ALLOW_CREATE_ORGANIZATION: false
          SHOW_REGISTRATION_BUTTON: false

        repository:
          DEFAULT_PRIVATE: private
          ENABLE_PUSH_CREATE_USER: false
          ENABLE_PUSH_CREATE_ORG: false

        ui:
          SHOW_USER_EMAIL: false

        openid:
          ENABLE_OPENID_SIGNIN: false
          ENABLE_OPENID_SIGNUP: false

        actions:
          ENABLED: false

        packages:
          ENABLED: false

        migrations:
          ALLOW_LOCALNETWORKS: false

        webhook:
          ALLOWED_HOST_LIST: external

        mailer:
          ENABLED: false

        metrics:
          ENABLED: true
