---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/flux/2.8.3/helmrelease_v2.json?values=app-template/4.6.2
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: searxng
  install:
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    remediation:
      retries: 1
  values:
    controllers:
      searxng:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: &uid 977
            runAsGroup: *uid
            fsGroup: *uid
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/searxng/searxng
              tag: 2026.3.29-c8208fa8b@sha256:a3454513393edad5ba4c9c4c928f76aca182581e0b93e8855da57891d8eafd23
            env:
              SEARXNG_BASE_URL: &url https://search.${SECRET_DOMAIN}
              SEARXNG_URL: *url
              SEARXNG_PORT: &port 8080
              UWSGI_WORKERS: 1
              UWSGI_THREADS: 4
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 1
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 2
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      main:
        controller: searxng
        ports:
          http:
            port: *port
    route:
      main:
        hostnames:
          - search.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port
    persistence:
      config:
        type: configMap
        name: searxng
        globalMounts:
          - path: /etc/searxng/settings.yml
            subPath: settings.yml
            readOnly: true
      tmp:
        type: emptyDir
    configMaps:
      config:
        data:
          settings.yml: |
            use_default_settings:
              engines:
                keep_only:
                  - google
                  - google images
                  - duckduckgo
                  - brave
                  - wikipedia

            server:
              secret_key: "397ac7172af69baf39ea068fc89b945a3f484ec3cd07fba56c459468bb575d9a"
              public_instance: false
              limiter: true
              image_proxy: true
              method: GET

            search:
              safe_search: 1
              autocomplete: google
              default_lang: en
              formats:
                - html
                - json

            ui:
              static_use_hash: true
              default_theme: simple
              theme_args:
                simple_style: dark
              infinite_scroll: true
              results_on_new_tab: false

            enabled_plugins:
              - Basic Calculator
              - Hash plugin
              - Self Information
              - Timezones plugin
              - Unit converter plugin
              - Tracker URL remover
              - Open Access DOI rewrite

            engines:
              - name: google
                weight: 2
                shortcut: g
              - name: duckduckgo
                weight: 1
                shortcut: ddg
              - name: brave
                weight: 1
                shortcut: br
              - name: google images
                weight: 2
                shortcut: gi

            outgoing:
              request_timeout: 2.0
              max_request_timeout: 5.0
